### ISSUE TITLE
RAC-A: Login messaging for AC-8

### ISSUE THREAD

**Issue by mogul** [18F/cg-uaa#15]
In order to comply with [NIST 800-53 AC-8](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-8) all users must acknowledge monitoring is in effect and see clear guidance on the usage of the system whenever they login at `https://login.fr.cloud.gov`.

**Acceptance Criteria**
- [ ] Users are forced to acknowledge the points in `AC-8 (a) (1-4)` before logging in (which meets `AC-8 (b)`)
- [ ] Users can find detailed information about the intended usage and conditions of their access (meeting `AC-8 (c)`)
- [ ] Users can find detailed information about the terms of service of cloud.gov (meeting `PS-??`)
- [ ] The specific content of our messaging has been reviewed by the OGC

**Implementation Sketch**
Here's what we came up with: 
![cg-agency-signin-hidden-button 2x](https://cloud.githubusercontent.com/assets/47762/16168544/1528cec2-34bf-11e6-918f-132178c2f542.png)

Notes from discussion:
- Careful not to lose the shading boundary separating the SAML and local login forms that's already in in production
- Content of short text should be `Your use of this US government service is monitored and recorded. Any misuse is subject to criminal and civil penalties.`
- Content of long text to be determined by consulting with OGC/GSA IT.

**Comment by mleibner** [comment]
Can user acknowledgement be combined into the same page as the login screen, rather than forcing the user to explicitly accept prior to being sent to the login screen in a second step?

I won't point to this as an example of good design (it's just the first thing I thought of), but other government sites like https://goes-app.cbp.dhs.gov/main/goes include the message on the same screen as the login form & don't require two steps.

I'd recommend getting rid of that Accept & Continue button if possible, and put that disclaimer above the login form, saving the user a step.

**Comment by thisisdano** [comment]
Yeah, I don't know if it's acceptable/desired simply to have a notice that says something like:

> Signing in to cloud.gov acknowledges that your use of this US government service is monitored and recorded. Any misuse is subject to criminal and civil penalties. Read more details.

`AC-8 (b)` says: 

> b. Retains the notification message or banner on the screen until users acknowledge the usage conditions and take explicit actions to log on to or further access the information system;

I don't know if the clause indicates that the explicit action to log on _itself_ can be considered to fulfill acknowledgement of the usage conditions. But if we just state that it does...

@mogul, do you have any additional guidance?

**Comment by thisisdano** [comment]
@marco, I started roughing this out on https://github.com/18F/cg-uaa/tree/dw-ac8

Now, assuming the functionality we outlined in the issue, we need:
1. All login modules to be hidden until the user confirms the notice.
2. The complete notice (currently set up in a modal) triggered when the user clicks on the link in the notice. (And be dismissable.)
3. Login modules to appear — and notice to disappear — when the user confirms the notice.

Does this page need javascript enabled to work? Should it work even without javascript?

**Comment by mogul** [comment]
> I don't know if the clause indicates that the explicit action to log on itself can be considered to fulfill acknowledgement of the usage conditions. But if we just state that it does...
> 
> @mogul, do you have any additional guidance?

Having seen no precedent system using it, I feel less confident that we'd pass muster that way, and we're a bit under the gun to have something passable in place by this Friday. So I'd say we can keep that in mind as UX debt to be revisited in future when we have better guidance available and more time to clear it.

> Does this page need javascript enabled to work? Should it work even without javascript?

Of course it would be great for it to work without Javascript, but so long as the non-Javascript state doesn't just let them waltz through (eg controls are hidden/disabled until Javscript enables them), I think it's fine to require Javascript.

**Comment by msecret** [comment]
I'd agree with Bret here, it doesn't need to work without javascript for now.

**Comment by thisisdano** [comment]
@marco, I'm gonna pull your js commit on my branch, do a quick check, and get a PR going for first thing tomorrow morning.

**Comment by thisisdano** [comment]
That worked great @msecret. Thank you.
I made a first pass at style polish on the modal. Here's how the whole flow works:

---

**User sees notice with link to read more or agree and continue:**

<img width="456" alt="screen shot 2016-06-21 at 5 41 06 pm" src="https://cloud.githubusercontent.com/assets/11464021/16251115/3b5b4a86-37d8-11e6-8994-de62b0f210fc.png">

---

**Read more details reveals the details in a dismissable modal.**

<img width="554" alt="screen shot 2016-06-21 at 5 45 11 pm" src="https://cloud.githubusercontent.com/assets/11464021/16251133/749838fe-37d8-11e6-8627-9bdd745db587.png">

---

**Selecting 'Agree and Continue' reveals the standard login options**

<img width="523" alt="screen shot 2016-06-21 at 5 45 28 pm" src="https://cloud.githubusercontent.com/assets/11464021/16251143/8bb5062a-37d8-11e6-9386-66f407b89d9a.png">

**Comment by thisisdano** [comment]
This first pass is addressed in a pull request: https://github.com/18F/cg-uaa/pull/18

**Comment by brittag** [comment]
I started a doc in our cloud.gov Google Drive folder for working on the longer text: https://docs.google.com/document/d/1Rr0P52p-0tRtnD17K3yEkjAGmGt0VSU55vUYAUsYB3k/edit#

**Comment by mogul** [comment]
It looks good in the staging environment, and will appear on https://login.cloud.gov and https://login.fr.cloud.gov shortly.

**Comment by mogul** [comment]
Deployed and live. This should be sufficient for compliance purposes. 

One bug report: In a small window, the pop-over text is cut-off and doesn't scroll: 
![image](https://cloud.githubusercontent.com/assets/47762/16346141/9ffb5ac0-39fa-11e6-9e6c-9f733f449157.png)

Resizing the window after that happens doesn't fix it... You have to reload with a larger window for it to work.

If this is a trivial fix, let's tackle it. Otherwise, feel free to note this on a separate card and throw it in the Icebox for a while.
