### ISSUE TITLE
hide warning message for return visitors?

### ISSUE THREAD

**Issue by afeld** [18F/cg-uaa#22]
It seems that the government warning thing appears every time you visit login.cloud.gov...does it need to? Could we hide it after the first time the user accepts, at least for some period of time?

/cc @thisisdano

**Comment by msecret** [comment]
I did ask about this, and was told to make it appear on every page load. Not sure if that decision was based on policy, law, or just easier to program.

**Comment by afeld** [comment]
Who could give us a definitive answer?

**Comment by msecret** [comment]
@brittag read the docs pretty thoroughly. @dlapiduz brought us this story.

**Comment by dlapiduz** [comment]
It needs to show every single time... yayyyy

**Comment by brittag** [comment]
For reference in case other people are interested in this in the future, this requirement is spelled out at https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-8
