### ISSUE TITLE
Forward to new dashboard

### ISSUE THREAD

**Issue by msecret** [18F/cg-uaa#25]
When a user goes straight to login.cloud.gov, they will be presented with a page with two buttons: Deck and Invite users after they login. The "Deck" button should instead point to the new dashboard

Acceptance criteria:
- [x] The icon for the deck shoudl be changed to an image of a dashboard (posted in comments)
- [x] The text for the deck icon should be "dashboard"
- [x] The link for the icon should go to dashboard.cloud.gov.

**Comment by msecret** [comment]
Here's the image that has to be replaced, it should be the right size:

![deck](https://cloud.githubusercontent.com/assets/1701077/16779855/dae8a1c4-4828-11e6-982e-45399af2767d.jpg)

This needs to be to the cloud.gov s3 so it replaces the link at `https://18f-cloud-gov.s3.amazonaws.com/deck.jpg`

**Comment by msecret** [comment]
Here's were the data for that page needs to be switched: https://github.com/18F/cg-deploy-cf/blob/636bd3c7b2c94e94716bcff2c8be236b21452267/cf-properties.yml#L310

**Comment by msecret** [comment]
Currently blocked on getting access to upload the S3 image.

**Comment by sharms** [comment]
`upload: ./dae8a1c4-4828-11e6-982e-45399af2767d.jpg to s3://18f-cloud-gov/deck.jpg`

**Comment by msecret** [comment]
We concluded that I should add the image to the dashboard at an accessible URL and then update the url for it in the cf-properties.yml file.

**Comment by msecret** [comment]
This is currently blocked by not being able to deploy cg-deploy-cf. I've asked the Atlas team to deploy it but it hasn't happened yet.
