### ISSUE TITLE
Invalid X-XSS-Protection header on login.cloud.gov

### ISSUE THREAD

**Issue by jseppi** [18F/cg-uaa#27]
<img width="554" alt="screen shot 2016-07-14 at 1 55 14 pm" src="https://cloud.githubusercontent.com/assets/697848/16851792/bee473f6-49ca-11e6-8248-4085a5aa635b.png">

We had the same problem in CALC: https://github.com/18F/calc/issues/363

The nginx proxy that cloud.gov uses sets some security headers (ref https://github.com/18F/cg-secureproxy-boshrelease/blob/master/jobs/secureproxy/templates/config/nginx.conf.erb#L107). The app is probably also setting these headers, leading to duplication that results in the browser having parsing problems.

Steps to reproduce:
1. Visit https://login.cloud.gov
2. Open Chrome Developer console where you will see the error logged

**Comment by afeld** [comment]
Sounds like this issue isn't actually specific to login.cloud.gov (the UAA)...?

**Comment by NoahKunin** [comment]
@afeld @jseppi Is this the desirable behavior? That is, let cloud.gov do this for all apps?

If not, what are you thinking is the desirable change?

**Comment by jmcarp** [comment]
@NoahKunin: here's what the team wrote up back in February: https://trello.com/c/P6DknfSK/659-avoid-duplication-of-xss-headers-in-nginx-secureproxy.

**Comment by jseppi** [comment]
@afeld: correct, it is not specific to login.cloud.gov

@NoahKunin: I think the desirable behavior is that the security headers are only added if they are not already present.

There is another related issue that the proxy does not add security headers to error responses (`400` and up), which leaves it up to application code to add them in those cases. I think they should be added to all responses (success and error) or none.

**Comment by afeld** [comment]
@jmcarp Still seeing the same behavior results described in https://github.com/18F/cg-product/issues/433#issue-185571285 — would you mind letting us know when/where we can confirm?

**Comment by jmcarp** [comment]
Yeah, secureproxy lives in the cf deployment, which takes kind of a long time. Will update when that's done.

**Comment by jmcarp** [comment]
The deploy finished, and now everything is perfect.
